import './globals.css'
import { Raleway } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';
import AuthContext from '@/context/AuthContext';

const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// 231112 루트레이아웃에서 redux provider 제거하고 [slug] 의 layout 으로 이동
const RootLayout = ({ children }) => {

  return (
    <html lang="kr">
      <body className={raleway.className}>
            <AuthContext>
              {children}
            </AuthContext>
          <Analytics />
      </body>
    </html>
  )
}

export default RootLayout